// Generated by swift_ffi. Do not edit.
//
// TypeScript bindings for the `SwiftUI` Swift module compiled to a
// WebAssembly reactor. Load with:
//
//   const bridge = await load(wasmBytesOrModule);
//
// Ownership follows the swift-java model: wrapper objects own a +1 handle
// to the Swift instance. Release deterministically with `close()` (or a
// `using` declaration); a FinalizationRegistry backstop releases leaked
// wrappers after they are garbage collected.
//
// The shared runtime (swift_ffi/runtime/ts) is staged next to this file
// by the wasm library macro; bridges in one directory share the one copy.
import { BlobReader, BlobWriter, Runtime, SwiftError, Tags, Types, decodeWith, decoder, encodeError, encodeErrorBlob, encodeWith, errorMessageOf, foreignObjects, nextCallId, pendingCalls, registerForeign, registry, resumeAsync, stageBytes, stageString, takeBytes, wasiShim, } from "./swift_ffi_runtime.js?v=4068686020";
// Re-exported so consumers keep importing them from this module.
export { Types } from "./swift_ffi_runtime.js?v=4068686020";
/** The runtime type token for `TextMetrics` (generic calls). */
export const TextMetricsType = {
    encode(w, v) {
        w.typeHeader(Tags.struct, "TextMetrics");
        w.i64(2n);
        Types.double.encode(w, v.width);
        Types.double.encode(w, v.height);
    },
    decode(r) {
        const tag = r.i32();
        const aux = r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected TextMetrics");
        if (aux > 0)
            r.bytes(aux);
        r.i64();
        const width = Types.double.decode(r);
        const height = Types.double.decode(r);
        return { width, height };
    },
};
/** The runtime type token for `ImageInfoValue` (generic calls). */
export const ImageInfoValueType = {
    encode(w, v) {
        w.typeHeader(Tags.struct, "ImageInfoValue");
        w.i64(3n);
        Types.int32.encode(w, v.state);
        Types.double.encode(w, v.width);
        Types.double.encode(w, v.height);
    },
    decode(r) {
        const tag = r.i32();
        const aux = r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected ImageInfoValue");
        if (aux > 0)
            r.bytes(aux);
        r.i64();
        const state = Types.int32.decode(r);
        const width = Types.double.decode(r);
        const height = Types.double.decode(r);
        return { state, width, height };
    },
};
/** The runtime type token for `StoredValue` (generic calls). */
export const StoredValueType = {
    encode(w, v) {
        w.typeHeader(Tags.struct, "StoredValue");
        w.i64(2n);
        Types.bool.encode(w, v.exists);
        Types.string.encode(w, v.contents);
    },
    decode(r) {
        const tag = r.i32();
        const aux = r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected StoredValue");
        if (aux > 0)
            r.bytes(aux);
        r.i64();
        const exists = Types.bool.decode(r);
        const contents = Types.string.decode(r);
        return { exists, contents };
    },
};
export const BridgeKeyType = {
    encode(w, v) {
        Types.string.encode(w, v);
    },
    decode(r) {
        return Types.string.decode(r);
    },
};
export class SwiftSocketBridge {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_visor_SocketBridge_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("SocketBridge used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_visor_SocketBridge_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    open(url) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, url);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SocketBridge_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.int32, result);
    }
    send(id, text) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        Types.string.encode(w, text);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SocketBridge_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    disconnect(id) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SocketBridge_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    next(id) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.int32.encode(w, id);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.string, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SocketBridge_invoke", handle, 3, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
    delay(milliseconds) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.int32.encode(w, milliseconds);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return undefined;
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SocketBridge_invoke", handle, 4, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `SocketBridge` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_SocketBridge(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.int32, impl.open(a0));
            }
            case 1: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.string.decode(r);
                impl.send(a0, a1);
                return new Uint8Array(0);
            }
            case 2: {
                const a0 = Types.int32.decode(r);
                impl.disconnect(a0);
                return new Uint8Array(0);
            }
            case 3: {
                const callId = Types.int32.decode(r);
                const a0 = Types.int32.decode(r);
                if (!runtime)
                    throw new SwiftError("SocketBridge.next is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.next(a0)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.string, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
            case 4: {
                const callId = Types.int32.decode(r);
                const a0 = Types.int32.decode(r);
                if (!runtime)
                    throw new SwiftError("SocketBridge.delay is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.delay(a0)).then((value) => resumeAsync(rt(), callId, new Uint8Array([0, 0, 0, 0, 0, 0, 0, 0])), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown SocketBridge method ordinal");
    };
}
export class SwiftHttpBridge {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_visor_HttpBridge_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("HttpBridge used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_visor_HttpBridge_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    request(method, url, body, authorization) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, method);
        Types.string.encode(w, url);
        Types.string.encode(w, body);
        Types.string.encode(w, authorization);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.string, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_HttpBridge_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `HttpBridge` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_HttpBridge(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                const a2 = Types.string.decode(r);
                const a3 = Types.string.decode(r);
                if (!runtime)
                    throw new SwiftError("HttpBridge.request is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.request(a0, a1, a2, a3)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.string, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown HttpBridge method ordinal");
    };
}
export class SwiftSettingsBridge {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_visor_SettingsBridge_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("SettingsBridge used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_visor_SettingsBridge_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    get(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SettingsBridge_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.string, result);
    }
    set(key, value) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        Types.string.encode(w, value);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_SettingsBridge_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `SettingsBridge` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_SettingsBridge(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.string, impl.get(a0));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.set(a0, a1);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown SettingsBridge method ordinal");
    };
}
export class SwiftCacheBridge {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_visor_CacheBridge_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("CacheBridge used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_visor_CacheBridge_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    snapshot(version) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, version);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_CacheBridge_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.string, result);
    }
    apply(ops) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, ops);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_visor_CacheBridge_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `CacheBridge` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_CacheBridge(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.int32.decode(r);
                return encodeWith(Types.string, impl.snapshot(a0));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                impl.apply(a0);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown CacheBridge method ordinal");
    };
}
export class SwiftGPUWebHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_GPUWebHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("GPUWebHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_GPUWebHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    gpuCreateTexture(id, width, height, rgba) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        Types.int32.encode(w, width);
        Types.int32.encode(w, height);
        Types.bytes.encode(w, rgba);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDestroyTexture(id) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuBeginFrame(red, green, blue, alpha) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.double.encode(w, red);
        Types.double.encode(w, green);
        Types.double.encode(w, blue);
        Types.double.encode(w, alpha);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuSetTransform(matrix) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, matrix);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 3, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDrawTextured(id, vertices) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        Types.bytes.encode(w, vertices);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 4, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDrawColor(vertices) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, vertices);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 5, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDrawRects(vertices) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, vertices);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 6, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuSetScissor(x, y, width, height) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, x);
        Types.int32.encode(w, y);
        Types.int32.encode(w, width);
        Types.int32.encode(w, height);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 7, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuClearScissor() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 8, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuEndFrame() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 9, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `GPUWebHost` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_GPUWebHost(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.int32.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.bytes.decode(r);
                impl.gpuCreateTexture(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 1: {
                const a0 = Types.int32.decode(r);
                impl.gpuDestroyTexture(a0);
                return new Uint8Array(0);
            }
            case 2: {
                const a0 = Types.double.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.double.decode(r);
                const a3 = Types.double.decode(r);
                impl.gpuBeginFrame(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.bytes.decode(r);
                impl.gpuSetTransform(a0);
                return new Uint8Array(0);
            }
            case 4: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.bytes.decode(r);
                impl.gpuDrawTextured(a0, a1);
                return new Uint8Array(0);
            }
            case 5: {
                const a0 = Types.bytes.decode(r);
                impl.gpuDrawColor(a0);
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.bytes.decode(r);
                impl.gpuDrawRects(a0);
                return new Uint8Array(0);
            }
            case 7: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.int32.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.int32.decode(r);
                impl.gpuSetScissor(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 8: {
                impl.gpuClearScissor();
                return new Uint8Array(0);
            }
            case 9: {
                impl.gpuEndFrame();
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown GPUWebHost method ordinal");
    };
}
export class SwiftWebHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_WebHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("WebHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_WebHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    measureText(text, fontSize, weight, wrapWidth) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, text);
        Types.double.encode(w, fontSize);
        Types.int32.encode(w, weight);
        Types.double.encode(w, wrapWidth);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(TextMetricsType, result);
    }
    imageInfo(source, isRemote) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, source);
        Types.bool.encode(w, isRemote);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(ImageInfoValueType, result);
    }
    syncHostViews(viewsJSON) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, viewsJSON);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    beginTextInput(text, x, y, width, height, fontSize) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, text);
        Types.double.encode(w, x);
        Types.double.encode(w, y);
        Types.double.encode(w, width);
        Types.double.encode(w, height);
        Types.double.encode(w, fontSize);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 3, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    endTextInput() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 4, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    scheduleRender() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 5, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    setColorScheme(dark) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bool.encode(w, dark);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 6, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    now() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 7, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.double, result);
    }
    rasterize(spec) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, spec);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 8, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bytes, result);
    }
    storageGet(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 9, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(StoredValueType, result);
    }
    storageSet(key, value) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        Types.string.encode(w, value);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 10, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    log(message) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, message);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 11, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    openURL(url) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, url);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 12, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    platformCommand(key, value) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        Types.string.encode(w, value);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 13, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    epochMillis() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 14, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.double, result);
    }
    renderTree(tree) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, tree);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 15, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    registerImage(source, bytes) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, source);
        Types.bytes.encode(w, bytes);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 16, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `WebHost` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_WebHost(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.double.decode(r);
                return encodeWith(TextMetricsType, impl.measureText(a0, a1, a2, a3));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                const a1 = Types.bool.decode(r);
                return encodeWith(ImageInfoValueType, impl.imageInfo(a0, a1));
            }
            case 2: {
                const a0 = Types.string.decode(r);
                impl.syncHostViews(a0);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.string.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.double.decode(r);
                const a3 = Types.double.decode(r);
                const a4 = Types.double.decode(r);
                const a5 = Types.double.decode(r);
                impl.beginTextInput(a0, a1, a2, a3, a4, a5);
                return new Uint8Array(0);
            }
            case 4: {
                impl.endTextInput();
                return new Uint8Array(0);
            }
            case 5: {
                impl.scheduleRender();
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.bool.decode(r);
                impl.setColorScheme(a0);
                return new Uint8Array(0);
            }
            case 7: {
                return encodeWith(Types.double, impl.now());
            }
            case 8: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.bytes, impl.rasterize(a0));
            }
            case 9: {
                const a0 = Types.string.decode(r);
                return encodeWith(StoredValueType, impl.storageGet(a0));
            }
            case 10: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.storageSet(a0, a1);
                return new Uint8Array(0);
            }
            case 11: {
                const a0 = Types.string.decode(r);
                impl.log(a0);
                return new Uint8Array(0);
            }
            case 12: {
                const a0 = Types.string.decode(r);
                impl.openURL(a0);
                return new Uint8Array(0);
            }
            case 13: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.platformCommand(a0, a1);
                return new Uint8Array(0);
            }
            case 14: {
                return encodeWith(Types.double, impl.epochMillis());
            }
            case 15: {
                const a0 = Types.bytes.decode(r);
                impl.renderTree(a0);
                return new Uint8Array(0);
            }
            case 16: {
                const a0 = Types.string.decode(r);
                const a1 = Types.bytes.decode(r);
                impl.registerImage(a0, a1);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown WebHost method ordinal");
    };
}
/** Builders wrapping host implementations for injection. */
export const Dependencies = {
    socketBridge: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_visor_SocketBridge",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_SocketBridge(impl, runtime)(args);
            },
        };
    },
    httpBridge: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_visor_HttpBridge",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_HttpBridge(impl, runtime)(args);
            },
        };
    },
    settingsBridge: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_visor_SettingsBridge",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_SettingsBridge(impl, runtime)(args);
            },
        };
    },
    cacheBridge: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_visor_CacheBridge",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_CacheBridge(impl, runtime)(args);
            },
        };
    },
    gPUWebHost: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_GPUWebHost",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_GPUWebHost(impl, runtime)(args);
            },
        };
    },
    webHost: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_WebHost",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_WebHost(impl, runtime)(args);
            },
        };
    },
};
export class SwiftUI {
    runtime;
    /** @internal */
    constructor(runtime) {
        this.runtime = runtime;
    }
    installVisorBridges(socket, http, settings) {
        const f0 = socket instanceof SwiftSocketBridge ? [socket.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_SocketBridge(socket, () => this.runtime))];
        const f1 = http instanceof SwiftHttpBridge ? [http.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_HttpBridge(http, () => this.runtime))];
        const f2 = settings instanceof SwiftSettingsBridge ? [settings.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_SettingsBridge(settings, () => this.runtime))];
        this.runtime.call("swift_ffi_visor_installVisorBridges", f0[0], f0[1], f1[0], f1[1], f2[0], f2[1]);
    }
    gpuConnect(host) {
        const f0 = host instanceof SwiftGPUWebHost ? [host.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_GPUWebHost(host, () => this.runtime))];
        this.runtime.call("swift_ffi_gpuConnect", f0[0], f0[1]);
    }
    uuiSetDisplayScale(scale) {
        this.runtime.call("swift_ffi_uuiSetDisplayScale", scale);
    }
    uuiStart(host, renderer, width, height) {
        const f0 = host instanceof SwiftWebHost ? [host.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_WebHost(host, () => this.runtime))];
        const b1 = stageString(this.runtime, renderer);
        this.runtime.call("swift_ffi_uuiStart", f0[0], f0[1], b1.ptr, b1.len, width, height);
        b1.drop();
    }
    uuiRender() {
        this.runtime.call("swift_ffi_uuiRender");
    }
    uuiMapSurfaceRender(id, camera, annotations, polygons, polylines, width, height) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, camera);
        const b2 = stageString(this.runtime, annotations);
        const b3 = stageString(this.runtime, polygons);
        const b4 = stageString(this.runtime, polylines);
        this.runtime.call("swift_ffi_uuiMapSurfaceRender", b0.ptr, b0.len, b1.ptr, b1.len, b2.ptr, b2.len, b3.ptr, b3.len, b4.ptr, b4.len, width, height);
        b0.drop();
        b1.drop();
        b2.drop();
        b3.drop();
        b4.drop();
    }
    uuiSetScenePhase(phase) {
        const b0 = stageString(this.runtime, phase);
        this.runtime.call("swift_ffi_uuiSetScenePhase", b0.ptr, b0.len);
        b0.drop();
    }
    uuiSetColorScheme(dark) {
        this.runtime.call("swift_ffi_uuiSetColorScheme", dark ? 1 : 0);
    }
    uuiOpenURL(url) {
        const b0 = stageString(this.runtime, url);
        this.runtime.call("swift_ffi_uuiOpenURL", b0.ptr, b0.len);
        b0.drop();
    }
    uuiPointerEvent(kind, x, y) {
        this.runtime.call("swift_ffi_uuiPointerEvent", kind, x, y);
    }
    uuiWheelEvent(x, y, deltaX, deltaY) {
        this.runtime.call("swift_ffi_uuiWheelEvent", x, y, deltaX, deltaY);
    }
    uuiResize(width, height) {
        this.runtime.call("swift_ffi_uuiResize", width, height);
    }
    uuiTextChanged(text) {
        const b0 = stageString(this.runtime, text);
        this.runtime.call("swift_ffi_uuiTextChanged", b0.ptr, b0.len);
        b0.drop();
    }
    uuiTextSubmitted() {
        this.runtime.call("swift_ffi_uuiTextSubmitted");
    }
    uuiTextEnded() {
        this.runtime.call("swift_ffi_uuiTextEnded");
    }
    uuiHostEvent(id, value) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_uuiHostEvent", b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
    uuiKeyEvent(id, value) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, value);
        const r = this.runtime.call("swift_ffi_uuiKeyEvent", b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
        return r !== 0;
    }
}
/** Instantiates the reactor and returns the bridged API. `wasi`
 * merges over the built-in WASI shim, so a host can extend or
 * replace individual calls (clocks, fds, …) without forking. */
export async function load(wasm, options) {
    let memory;
    let runtime;
    // Buffer helpers for the dispatch channel: buffers arrive as
    // (ptr, len) borrowed and return packed as (len << 32) | ptr with
    // bytes from swift_ffi_alloc, ownership transferred to the guest.
    const foreignBytes = (ptr, len) => len === 0 ? new Uint8Array(0) : new Uint8Array(memory.buffer, ptr, len).slice();
    const foreignString = (ptr, len) => len === 0 ? "" : decoder.decode(new Uint8Array(memory.buffer, ptr, len));
    const packForeignBytes = (bytes) => {
        if (bytes.length === 0)
            return 0n;
        const ptr = runtime.call("swift_ffi_alloc", bytes.length);
        new Uint8Array(memory.buffer, ptr, bytes.length).set(bytes);
        return (BigInt(bytes.length) << 32n) | BigInt(ptr >>> 0);
    };
    const swiftFFIImports = {
        closure_invoke: (id, argsPtr, argsLen) => {
            const dispatcher = foreignObjects.get(id);
            let result;
            try {
                if (!dispatcher)
                    throw new Error(`no foreign object ${id}`);
                result = dispatcher(foreignBytes(argsPtr, argsLen));
            }
            catch (error) {
                result = encodeErrorBlob(error instanceof Error ? error.message : String(error));
            }
            return packForeignBytes(result);
        },
        foreign_release: (id) => {
            foreignObjects.delete(id);
        },
        dependency_get: (keyPtr, keyLen) => {
            const dep = options?.dependencies?.[foreignString(keyPtr, keyLen)];
            if (!dep)
                return 0n;
            const w = new BlobWriter();
            w.header(Tags.list, 0);
            w.i64(3n);
            Types.bool.encode(w, dep.lazy);
            Types.string.encode(w, dep.key);
            Types.int32.encode(w, registerForeign((args) => dep.dispatcher(args, () => runtime)));
            return packForeignBytes(w.data());
        },
        task_enqueue: (job) => {
            queueMicrotask(() => {
                runtime.call("swift_ffi_task_run", job);
            });
        },
        // A timed job (Task.sleep): run it once the delay is up.
        task_enqueue_after: (job, delayMs) => {
            setTimeout(() => {
                runtime.call("swift_ffi_task_run", job);
            }, Math.max(0, delayMs));
        },
        async_complete: (callId, blobPtr, blobLen) => {
            const pending = pendingCalls.get(callId);
            pendingCalls.delete(callId);
            pending.resolve(pending.decode(foreignBytes(blobPtr, blobLen)));
        },
    };
    const imports = {
        wasi_snapshot_preview1: wasiShim(() => {
            if (!memory)
                throw new Error("wasm memory accessed before instantiation");
            return memory;
        }, options?.wasi),
        swift_ffi: swiftFFIImports,
    };
    const module = wasm instanceof WebAssembly.Module ? wasm : await WebAssembly.compile(wasm);
    const instance = await WebAssembly.instantiate(module, imports);
    memory = instance.exports.memory;
    instance.exports._initialize();
    runtime = new Runtime(instance.exports);
    // Register the interfaces' dependency-proxy factories (docs/wasm_di.md).
    runtime.call("swift_ffi_visor_register_SocketBridge");
    runtime.call("swift_ffi_visor_register_HttpBridge");
    runtime.call("swift_ffi_visor_register_SettingsBridge");
    runtime.call("swift_ffi_visor_register_CacheBridge");
    runtime.call("swift_ffi_register_GPUWebHost");
    runtime.call("swift_ffi_register_WebHost");
    return new SwiftUI(runtime);
}
